<?php 
    error_reporting(0);
    ini_set(“display_errors”, 0 );
    set_time_limit(0);

    //include "protege_professor.php";

    ini_set("upload_max_filesize", "10M");
    ini_set("max_execution_time", "-1");
    ini_set("memory_limit", "-1");
    ini_set("realpath_cache_size", "-1");
    if (!isset($_SESSION)) {
      session_start();
    }
?>

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Mirrored from seantheme.com/color-admin-v3.0/admin/html/table_manage_combine.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 04 Mar 2018 17:24:02 GMT -->
<head>
	<meta charset="utf-8" />
	<title>Immobile business</title>
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	
	<!-- ================== BEGIN BASE CSS STYLE ================== -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
	<link href="https://immobilebusiness.com.br/admin//assets/plugins/jquery-ui/themes/base/minified/jquery-ui.min.css" rel="stylesheet" />
	<link href="https://immobilebusiness.com.br/admin/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
	<link href="https://immobilebusiness.com.br/admin/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
	<link href="https://immobilebusiness.com.br/admin/assets/css/animate.min.css" rel="stylesheet" />
	<link href="https://immobilebusiness.com.br/admin/assets/css/style.min.css" rel="stylesheet" />
	<link href="https://immobilebusiness.com.br/admin/assets/css/style-responsive.min.css" rel="stylesheet" />
	<link href="https://immobilebusiness.com.br/admin/assets/css/theme/default.css" rel="stylesheet" id="theme" />
	<!-- ================== END BASE CSS STYLE ================== -->
	
	<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.1/bootstrap-editable/css/bootstrap-editable.css" />
	<!-- ================== END PAGE LEVEL STYLE ================== -->
	

    <link rel="stylesheet" href="css/acc-wizard.min.css" />

	<!-- ================== BEGIN BASE JS ================== -->
	<script src="https://immobilebusiness.com.br/admin/assets/plugins/pace/pace.min.js"></script>

    <style type="text/css">
    	/* ----------------------------------------------
    	 * Generated by Animista on 2019-8-17 9:58:11
    	 * w: http://animista.net, t: @cssanimista
    	 * ---------------------------------------------- */

    	/**
    	 * ----------------------------------------
    	 * animation bounce-top
    	 * ----------------------------------------
    	 */
    	@-webkit-keyframes bounce-top {
    	  0% {
    	    -webkit-transform: translateY(-45px);
    	            transform: translateY(-45px);
    	    -webkit-animation-timing-function: ease-in;
    	            animation-timing-function: ease-in;
    	    opacity: 1;
    	  }
    	  24% {
    	    opacity: 1;
    	  }
    	  40% {
    	    -webkit-transform: translateY(-24px);
    	            transform: translateY(-24px);
    	    -webkit-animation-timing-function: ease-in;
    	            animation-timing-function: ease-in;
    	  }
    	  65% {
    	    -webkit-transform: translateY(-12px);
    	            transform: translateY(-12px);
    	    -webkit-animation-timing-function: ease-in;
    	            animation-timing-function: ease-in;
    	  }
    	  82% {
    	    -webkit-transform: translateY(-6px);
    	            transform: translateY(-6px);
    	    -webkit-animation-timing-function: ease-in;
    	            animation-timing-function: ease-in;
    	  }
    	  93% {
    	    -webkit-transform: translateY(-4px);
    	            transform: translateY(-4px);
    	    -webkit-animation-timing-function: ease-in;
    	            animation-timing-function: ease-in;
    	  }
    	  25%,
    	  55%,
    	  75%,
    	  87% {
    	    -webkit-transform: translateY(0px);
    	            transform: translateY(0px);
    	    -webkit-animation-timing-function: ease-out;
    	            animation-timing-function: ease-out;
    	  }
    	  100% {
    	    -webkit-transform: translateY(0px);
    	            transform: translateY(0px);
    	    -webkit-animation-timing-function: ease-out;
    	            animation-timing-function: ease-out;
    	    opacity: 1;
    	  }
    	}
    	@keyframes bounce-top {
    	  0% {
    	    -webkit-transform: translateY(-45px);
    	            transform: translateY(-45px);
    	    -webkit-animation-timing-function: ease-in;
    	            animation-timing-function: ease-in;
    	    opacity: 1;
    	  }
    	  24% {
    	    opacity: 1;
    	  }
    	  40% {
    	    -webkit-transform: translateY(-24px);
    	            transform: translateY(-24px);
    	    -webkit-animation-timing-function: ease-in;
    	            animation-timing-function: ease-in;
    	  }
    	  65% {
    	    -webkit-transform: translateY(-12px);
    	            transform: translateY(-12px);
    	    -webkit-animation-timing-function: ease-in;
    	            animation-timing-function: ease-in;
    	  }
    	  82% {
    	    -webkit-transform: translateY(-6px);
    	            transform: translateY(-6px);
    	    -webkit-animation-timing-function: ease-in;
    	            animation-timing-function: ease-in;
    	  }
    	  93% {
    	    -webkit-transform: translateY(-4px);
    	            transform: translateY(-4px);
    	    -webkit-animation-timing-function: ease-in;
    	            animation-timing-function: ease-in;
    	  }
    	  25%,
    	  55%,
    	  75%,
    	  87% {
    	    -webkit-transform: translateY(0px);
    	            transform: translateY(0px);
    	    -webkit-animation-timing-function: ease-out;
    	            animation-timing-function: ease-out;
    	  }
    	  100% {
    	    -webkit-transform: translateY(0px);
    	            transform: translateY(0px);
    	    -webkit-animation-timing-function: ease-out;
    	            animation-timing-function: ease-out;
    	    opacity: 1;
    	  }
    	}


    	/* ----------------------------------------------
    	 * Generated by Animista on 2019-8-17 9:52:23
    	 * w: http://animista.net, t: @cssanimista
    	 * ---------------------------------------------- */

    	/**
    	 * ----------------------------------------
    	 * animation jello-horizontal
    	 * ----------------------------------------
    	 */
    	@-webkit-keyframes jello-horizontal {
    	  0% {
    	    -webkit-transform: scale3d(1, 1, 1);
    	            transform: scale3d(1, 1, 1);
    	  }
    	  30% {
    	    -webkit-transform: scale3d(1.25, 0.75, 1);
    	            transform: scale3d(1.25, 0.75, 1);
    	  }
    	  40% {
    	    -webkit-transform: scale3d(0.75, 1.25, 1);
    	            transform: scale3d(0.75, 1.25, 1);
    	  }
    	  50% {
    	    -webkit-transform: scale3d(1.15, 0.85, 1);
    	            transform: scale3d(1.15, 0.85, 1);
    	  }
    	  65% {
    	    -webkit-transform: scale3d(0.95, 1.05, 1);
    	            transform: scale3d(0.95, 1.05, 1);
    	  }
    	  75% {
    	    -webkit-transform: scale3d(1.05, 0.95, 1);
    	            transform: scale3d(1.05, 0.95, 1);
    	  }
    	  100% {
    	    -webkit-transform: scale3d(1, 1, 1);
    	            transform: scale3d(1, 1, 1);
    	  }
    	}
    	@keyframes jello-horizontal {
    	  0% {
    	    -webkit-transform: scale3d(1, 1, 1);
    	            transform: scale3d(1, 1, 1);
    	  }
    	  30% {
    	    -webkit-transform: scale3d(1.25, 0.75, 1);
    	            transform: scale3d(1.25, 0.75, 1);
    	  }
    	  40% {
    	    -webkit-transform: scale3d(0.75, 1.25, 1);
    	            transform: scale3d(0.75, 1.25, 1);
    	  }
    	  50% {
    	    -webkit-transform: scale3d(1.15, 0.85, 1);
    	            transform: scale3d(1.15, 0.85, 1);
    	  }
    	  65% {
    	    -webkit-transform: scale3d(0.95, 1.05, 1);
    	            transform: scale3d(0.95, 1.05, 1);
    	  }
    	  75% {
    	    -webkit-transform: scale3d(1.05, 0.95, 1);
    	            transform: scale3d(1.05, 0.95, 1);
    	  }
    	  100% {
    	    -webkit-transform: scale3d(1, 1, 1);
    	            transform: scale3d(1, 1, 1);
    	  }
    	}


        @media screen and (max-width: 600px) {
        	ol.acc-wizard-sidebar{
        		display: none;
        	}
        }

        strong{
        	font-size: 14px!important;
        	font-weight: 500!important;
        }
      	
      	.panel > .panel-heading {
      	    background-image: none;
      	    background-color: #00728C;
      	    color: white;

      	}

      	/*div.shadow {
      	  box-shadow:-4px 11px 11px grey;
      	}*/

      	.animate-text:hover {
      		-webkit-animation: jello-horizontal 1s 0.3s 1 both;
      		        animation: jello-horizontal 1s 0.3s 1 both;
      	}


      	.bounce-top {
      		-webkit-animation: bounce-top 1s both;
      		        animation: bounce-top 1s both;
      	}
    </style>
	<!-- ================== END BASE JS ================== -->
</head>
<body>
	<!-- begin #page-loader -->
	<div id="page-loader" class="fade in"><span class="spinner"></span></div>
	<!-- end #page-loader -->
    <div id="page-container" class="fade page-header-fixed page-sidebar-fixed">
    <!-- begin #header -->
    <?php include "topo.php";?>

    <div class="sidebar-bg"></div>
		<div id="content" class="content">

			<div class="panel panel-info">
				<div class="panel-heading" style="height: 150%;">
					<h4 class="panel-title">
						<a href="#simulacao" data-parent="#accordion-demo" data-toggle="collapse" style="text-transform: uppercase; font-size: 14px;">
							Simulação de Venda
						</a>
					</h4>
				</div>

				<div class="panel-body">
					<div class="row" id="especial" >
						<div class="panel-body col-md-8">
							<div class="row acc-wizard">
								<div class="col-md-4">
									<ol class="acc-wizard-sidebar">
										<li class="acc-wizard-todo animate-text"><a href="#avista" style="font-size: 16px; text-transform: uppercase;">A vista</a></li>
										<li class="acc-wizard-todo animate-text"><a href="#entrada" style="font-size: 16px; text-transform: uppercase;">Entrada</a></li>
										<li class="acc-wizard-todo animate-text"><a  href="#intermediaria" style="font-size: 16px; text-transform: uppercase;">Intermediaria</a></li>
										<li class="acc-wizard-todo acc-wizard-active animate-text"><a href="#parcela_unica" style="font-size: 16px; text-transform: uppercase;">Parcela Única</a></li>
										<li class="acc-wizard-todo animate-text"><a href="#parcelamento" style="font-size: 16px; text-transform: uppercase;">Parcelamento</a></li>
										<li class="acc-wizard-todo animate-text"><a href="#" style="font-size: 16px; text-transform: uppercase;">Cliente</a></li>
									</ol>
								</div>

								<div class="col-md-8" style="padding-right: 2em;">
									<div id="accordion-demo" class="panel-group">
										
										<div class="panel panel-info">
											<div class="panel-heading" style="height: 150%;">
												<div class="panel-heading-btn">
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
												</div>
												<h4 class="panel-title">
													<a href="#avista" class="animate-text" data-parent="#accordion-demo" data-toggle="collapse" style="text-transform: uppercase; font-size: 14px;">
														A vista
													</a>
												</h4>
											</div>
											<div id="avista" class="panel-collapse collapse" style="height: 36.4px;">
												<div class="panel-body">
													<div class="form-group">
														<label for="avista">Digite o Valor da Parcela Unica</label>
														<input class="form-control" id="avista" money >	
													</div>

													<div class="acc-wizard-step">
														<button class="btn btn-primary" type="submit">Próxima Etapa</button>
													</div>
												</div> 
											</div> 
										</div>

										<div class="panel panel-info">
											<div class="panel-heading" style="height: 150%;">
												<div class="panel-heading-btn">
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
												</div>
												<h4 class="panel-title">
													<a href="#entrada" class="animate-text" data-parent="#accordion-demo" data-toggle="collapse" style="text-transform: uppercase; font-size: 14px;">
														Parcelas de Entrada
													</a>
												</h4>
											</div>
											<div id="entrada" class="panel-collapse collapse" style="height: 36.4px;">
												<div class="panel-body">
													<div class="form-group" id="modifica_entrada_original">

														<label for="parcelamento_entrada">Selecione a Forma de Entrada</label>
														<select class="form-control" id="parcelamento_entrada">
															<option>Selecione</option>
														</select>

													</div>

													<label><input type="checkbox" value="modifica_entrada"> Desejo Escolher A Entrada</label>

													<div class="form-group hidden" id="modifica_entrada">
														<label for="parcela_unica">Digite o Valor da Parcela Unica</label>
														<input class="form-control" type="text" money>	
													</div>

													<div class="form-group hidden" id="modifica_entrada">
														<label for="parcela_unica">Digite o Número de Vezes</label>
														<input class="form-control" type="number">	
													</div>

													<div class="acc-wizard-step">
														<button class="btn btn-primary" type="submit">Próxima Etapa</button>
													</div>
												</div> 
											</div> 
										</div>

										<div class="panel panel-info">
											<div class="panel-heading" style="height: 150%;">
												<div class="panel-heading-btn">
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
												</div>
												<h4 class="panel-title">
													<a href="#intermediaria"  class="animate-text" data-parent="#accordion-demo" data-toggle="collapse" style="text-transform: uppercase; font-size: 14px;">
														Parcelas Intermediárias
													</a>
												</h4>
											</div>
											<div id="intermediaria" class="panel-collapse collapse" style="height: 36.4px;">
												<div class="panel-body">
													<div class="form-group" id="modifica_intermediaria_original">

														<label for="parcelamento_intermediaria">Selecione a Forma das Intermediarias</label>
														<select class="form-control" id="parcelamento_intermediaria">
															<option>Selecione</option>
														</select>

													</div>

													<label><input type="checkbox" value="modifica_intermediaria"> Desejo Escolher A Intermediaria</label>

													<div class="form-group hidden" id="modifica_intermediaria">
														<label for="manual_intermediaria">Digite o Valor da Intermediaria</label>
														<input class="form-control" type="text" id="manual_intermediaria" money>	
													</div>

													<div class="form-group hidden" id="modifica_intermediaria">
														<label for="manual_intermediaria_vezes">Digite o Número de Vezes</label>
														<input class="form-control" type="number" id="manual_intermediaria_vezes">	
													</div>

													<div class="acc-wizard-step">
														<button class="btn btn-primary" type="submit">Próxima Etapa</button>
													</div>
												</div> 
											</div> 
										</div>

										<div class="panel panel-info">
											<div class="panel-heading" style="height: 150%;">
												<div class="panel-heading-btn">
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
												</div>
												<h4 class="panel-title">
													<a href="#parcela_unica" class="animate-text" data-parent="#accordion-demo" data-toggle="collapse" style="text-transform: uppercase; font-size: 14px;">
														Parcela Única
													</a>
												</h4>
											</div>
											<div id="parcela_unica" class="panel-collapse collapse" style="height: 36.4px;">
												<div class="panel-body">
													<div class="form-group">
														<label for="parcela_unica">Digite o Valor da Parcela Unica</label>
														<input class="form-control" id="parcela_unica" money >	
													</div>

													<div class="acc-wizard-step">
														<button class="btn btn-primary" type="submit">Próxima Etapa</button>
													</div>
												</div> 
											</div> 
										</div>

										<div class="panel panel-info">
											<div class="panel-heading" style="height: 150%;">
												<div class="panel-heading-btn">
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
													<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
												</div>
												<h4 class="panel-title">
													<a href="#parcelamento" class="animate-text" data-parent="#accordion-demo" data-toggle="collapse" style="text-transform: uppercase; font-size: 14px;">
														Parcelas Financiamento
													</a>
												</h4>
											</div>
											<div id="parcelamento" class="panel-collapse collapse" style="height: 36.4px;">
												<div class="panel-body">
													<div class="form-group" id="modifica_financiamento_original">

														<label for="parcelamento_financiamento">Selecione a Forma do Financiamento</label>
														<select class="form-control" id="parcelamento_financiamento">
															<option>Selecione</option>
														</select>

													</div>

													<label><input type="checkbox" value="modifica_financiamento"> Desejo Escolher A forma do Financiamento</label>

													<div class="form-group hidden" id="modifica_financiamento">
														<label for="manual_financiamento">Digite o Valor do Financiamento</label>
														<input class="form-control" type="text" id="manual_financiamento" money>	
													</div>

													<div class="form-group hidden" id="modifica_financiamento">
														<label for="manual_financiamento_vezes">Digite o Número de Vezes</label>
														<input class="form-control" type="number" id="manual_financiamento_vezes">	
													</div>


													<div class="acc-wizard-step">
														<button class="btn btn-primary" type="submit">Próxima Etapa</button>
													</div>
												</div> 
											</div> 
										</div>

									</div>
								</div>
							</div>
						</div> 

						<div class="alert alert-success col-md-4 shadow" style="padding: 10px; background-color:#FFF; color: #000; height: 250px;">
							<h4 class="alert-heading" style="text-align: center; font-size: 24px; font-weight: 600;">SIMULAÇÃO DE COMPRA</h4>

							<form >
								
								<div class="form-group" style="margin: 2px;">
									<strong>A vista</strong>
									<input type="text" class="form-control" style="color: #000; font-weight: 600; font-size: 18px;" disabled value="R$ 10.000,00">
								</div>

								<div class="form-group" style="margin: 2px;">
									<strong>Entrada:</strong>
									<input type="text" class="form-control" style="color: #000; font-weight: 600; font-size: 18px;" disabled value="5 x R$ 2.000,00 ">
								</div>

								<div class="form-group" style="margin: 2px;">
									<strong>Intermediaria:</strong>
									<input type="text" class="form-control" style="color: #000; font-weight: 600; font-size: 18px;" disabled value="5 x R$ 2.000,00 ">
								</div>

								<div class="form-group" style="margin: 2px;">
									<strong>Parcela Unica:</strong>
									<input type="text" class="form-control" style="color: #000; font-weight: 600; font-size: 18px;" disabled value="R$ 10.000,00">
								</div>

								<div class="form-group" style="margin: 2px;">
									<strong>Financiamento:</strong>
									<input type="text" class="form-control" style="color: #000; font-weight: 600; font-size: 18px;" disabled value="120 x R$ 500,00 ">
								</div>

								<div class="form-group" style="margin: 2px;">
									<strong>Valor do Lote:</strong>
									<input type="text" class="form-control" style="color: red; font-weight: 600; font-size: 18px;" disabled value="R$ 120.000,00">
								</div>

							</form>
						</div>

					</div>
				</div> 
			</div>
		</div>
		
	<!-- ================== BEGIN BASE JS ================== -->
	<script src="https://immobilebusiness.com.br/admin/assets/plugins/jquery/jquery-1.9.1.min.js"></script>
	<script src="https://immobilebusiness.com.br/admin/assets/plugins/jquery/jquery-migrate-1.1.0.min.js"></script>
	<script src="https://immobilebusiness.com.br/admin/assets/plugins/jquery-ui/ui/minified/jquery-ui.min.js"></script>
	<script src="https://immobilebusiness.com.br/admin/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
	<!--[if lt IE 9]>
		<script src="assets/crossbrowserjs/html5shiv.js"></script>
		<script src="assets/crossbrowserjs/respond.min.js"></script>
		<script src="assets/crossbrowserjs/excanvas.min.js"></script>
	<![endif]-->
	<script src="https://immobilebusiness.com.br/admin/assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>
	<script src="https://immobilebusiness.com.br/admin/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
	<!-- ================== END BASE JS ================== -->
	
	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	
	<script src="https://immobilebusiness.com.br/admin/assets/js/apps.min.js"></script>
    <script src="js/acc-wizard.js"></script>

	<!-- ================== END PAGE LEVEL JS ================== -->


	
	<script>
		$(document).ready(function() {
			App.init();

            $(".acc-wizard").accwizard();

            var aux = ($(window).height() - 200);
            $("div#especial").css('min-height', aux);
           

            $('input[type="checkbox"]').click(function(){

            	if($(this).attr('checked') == "checked"){

            		let para = $(this).val();

            		$('div#'+para).each(function(){
            			$(this).removeClass('hidden');
            		});

            		$('div#'+para+'_original').each(function(){
            			$(this).addClass('hidden');
            		});

            	}else{
            		let para = $(this).val();

            		$('div#'+para).each(function(){
            			$(this).addClass('hidden');
            		});

            		$('div#'+para+'_original').each(function(){
            			$(this).removeClass('hidden');
            		});

            	}
            });

            //EFEITOS PARA APLICAR MASCARA DE DINHEIRO 
            $(document).on('blur', 'input[money]', function(){

            	let aux = $(this).val();

            	aux = parseFloat(aux.replace(/[R$. ]/g, '').replace(/,/g, '.'));

            	isNaN(aux) ? aux = 0 : '';

            	aux = aux.toLocaleString('pt-br',{style: 'currency', currency: 'BRL'});

            	console.log(aux);
            	$(this).val(aux);
            });


            //EFEITOS PARA APLICAR MASCARA DE DINHEIRO
            $(document).on('focus', 'input[money]', function(){
            	$(this).val('');
            });


		});

	</script>
</body>

<!-- Mirrored from seantheme.com/color-admin-v3.0/admin/html/table_manage_combine.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 04 Mar 2018 17:24:03 GMT -->
</html>
